#ifndef SIGLENT2CSV_H
#define SIGLENT2CSV_H

#define HEADER_SIZE_BYTES 2048

#define OFFSET_TO_CH1_ON 0x00

#define OFFSET_TO_CH2_ON 0x04

#define OFFSET_TO_CH3_ON 0x08

#define OFFSET_TO_CH4_ON 0x0C

#define OFFSET_TO_CH1_VOLT_DIV_VAL 0x10
#define OFFSET_TO_CH1_VOLT_DIV_VAL_UNITS 0x1C
#define OFFSET_TO_CH1_VOLT_DIV_VAL_UNITS_MAGNITUDE 0x18

#define OFFSET_TO_CH2_VOLT_DIV_VAL 0x20
#define OFFSET_TO_CH2_VOLT_DIV_VAL_UNITS 0x2C
#define OFFSET_TO_CH2_VOLT_DIV_VAL_UNITS_MAGNITUDE 0x28

#define OFFSET_TO_CH3_VOLT_DIV_VAL 0x30
#define OFFSET_TO_CH3_VOLT_DIV_VAL_UNITS 0x3C
#define OFFSET_TO_CH3_VOLT_DIV_VAL_UNITS_MAGNITUDE 0x38

#define OFFSET_TO_CH4_VOLT_DIV_VAL 0x40
#define OFFSET_TO_CH4_VOLT_DIV_VAL_UNITS 0x4C
#define OFFSET_TO_CH4_VOLT_DIV_VAL_UNITS_MAGNITUDE 0x48

#define UNITS_V 0
#define UNITS_A 1
#define UNITS_VV 2
#define UNITS_AA 3
#define UNITS_OU 4
#define UNITS_W 5
#define UNITS_SQRT_V 6
#define UNITS_SQRT_A 6
#define UNITS_INTEGRAL_V 8
#define UNITS_INTEGRAL_A 9
#define UNITS_DT_V 10
#define UNITS_DT_A 11
#define UNITS_DT_DIV 12
#define UNITS_HZ 13
#define UNITS_S 14
#define UNITS_SA 15
#define UNITS_PTS 16
#define UNITS_NULL 17
#define UNITS_DB 18
#define UNITS_DBV 19
#define UNITS_DBA 20
#define UNITS_VPP 21
#define UNITS_VDC 22
#define UNITS_DBM 23

#define UNITS_MAGNITUDE_YOCTO 0
#define UNITS_MAGNITUDE_ZEPTO 1
#define UNITS_MAGNITUDE_ATTO 2
#define UNITS_MAGNITUDE_FEMTO 3
#define UNITS_MAGNITUDE_PICO 4
#define UNITS_MAGNITUDE_NANO 5
#define UNITS_MAGNITUDE_MICRO 6
#define UNITS_MAGNITUDE_MILLI 7
#define UNITS_MAGNITUDE_IU 8
#define UNITS_MAGNITUDE_KILO 9
#define UNITS_MAGNITUDE_MEGA 10
#define UNITS_MAGNITUDE_GIGA 11
#define UNITS_MAGNITUDE_TERA 12
#define UNITS_MAGNITUDE_PETA 13

#define OFFSET_TO_CH1_VERT_OFFSET 0x50
#define OFFSET_TO_CH1_VERT_OFFSET_UNITS 0x5C
#define OFFSET_TO_CH1_VERT_OFFSET_UNITS_MAGNITUDE 0x58

#define OFFSET_TO_CH2_VERT_OFFSET 0x60
#define OFFSET_TO_CH2_VERT_OFFSET_UNITS 0x6C
#define OFFSET_TO_CH2_VERT_OFFSET_UNITS_MAGNITUDE 0x68

#define OFFSET_TO_CH3_VERT_OFFSET 0x70
#define OFFSET_TO_CH3_VERT_OFFSET_UNITS 0x7C
#define OFFSET_TO_CH3_VERT_OFFSET_UNITS_MAGNITUDE 0x78

#define OFFSET_TO_CH4_VERT_OFFSET 0x80
#define OFFSET_TO_CH4_VERT_OFFSET_UNITS 0x8C
#define OFFSET_TO_CH4_VERT_OFFSET_UNITS_MAGNITUDE 0x88

#define OFFSET_TO_DIGITAL_ON 0x90

#define OFFSET_TO_D0_ON 0x94
#define OFFSET_TO_D1_ON 0x98
#define OFFSET_TO_D2_ON 0x9C
#define OFFSET_TO_D3_ON 0xA0
#define OFFSET_TO_D4_ON 0xA4
#define OFFSET_TO_D5_ON 0xA8
#define OFFSET_TO_D6_ON 0xAC
#define OFFSET_TO_D7_ON 0xB0
#define OFFSET_TO_D8_ON 0xB4
#define OFFSET_TO_D9_ON 0xB8
#define OFFSET_TO_D10_ON 0xBC
#define OFFSET_TO_D11_ON 0xC0
#define OFFSET_TO_D12_ON 0xC4
#define OFFSET_TO_D13_ON 0xC8
#define OFFSET_TO_D14_ON 0xCC
#define OFFSET_TO_D15_ON 0xD0

#define OFFSET_TO_TIME_DIV 0xD4
#define OFFSET_TO_TIME_DIV_UNITS 0xE0
#define OFFSET_TO_TIME_DIV_UNITS_MAGNITUDE 0xDC

#define OFFSET_TO_TIME_DELAY 0xE4
#define OFFSET_TO_TIME_DELAY_UNITS 0xF0
#define OFFSET_TO_TIME_DELAY_UNITS_MAGNITUDE 0xEC

#define OFFSET_TO_WAVE_LENGTH 0xF4

#define OFFSET_TO_SAMPLE_RATE 0xF8
#define OFFSET_TO_SAMPLE_RATE_UNITS 0x104
#define OFFSET_TO_SAMPLE_RATE_UNITS_MAGNITUDE 0x100

#define OFFSET_TO_DIGITAL_WAVE_LENGTH 0x108

#define OFFSET_TO_DIGITAL_SAMPLE_RATE 0x10C
#define OFFSET_TO_DIGITAL_SAMPLE_RATE_UNITS 0x118
#define OFFSET_TO_DIGITAL_SAMPLE_RATE_UNITS_MAGNITUDE 0x114

#define OFFSET_TO_ANALOG_DATA 0x800

#define CODE_PER_DIV 25 // "total data code in a horizontal division, on SDS1000X is 25" according to Siglent documentation. Not sure what exactly this means.

#endif // SIGLENT2CSV_H
